Thu Jul 06 09:25:11 CEST 2017 Thread[main,5,main] Cleanup action starting
java.sql.SQLException: Database 'Database\MAIN_CATS_DB' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue_browser_dao.DatabaseManager.getMainDBConnection(DatabaseManager.java:97)
	at catalogue_browser_dao.DatabaseManager.startMainDB(DatabaseManager.java:146)
	at ui_main_panel.CatalogueBrowserMain.main(CatalogueBrowserMain.java:47)
Caused by: ERROR XJ004: Database 'Database\MAIN_CATS_DB' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 19 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'Database\MAIN_CATS_DB' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue_browser_dao.DatabaseManager.getMainDBConnection(DatabaseManager.java:97)
	at catalogue_browser_dao.DatabaseManager.startMainDB(DatabaseManager.java:146)
	at ui_main_panel.CatalogueBrowserMain.main(CatalogueBrowserMain.java:47)
============= end nested exception, level (1) ===========
Cleanup action completed
----------------------------------------------------------------
Thu Jul 06 09:25:11 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance a816c00e-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\MAIN_CATS_DB with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
Thu Jul 06 09:25:28 CEST 2017 Thread[Thread-7,5,main] Cleanup action starting
java.sql.SQLException: Database 'Database\TEST_CATS\CAT_CATUSERS_DB\CATUSERS_VERSION_1.0' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
Caused by: ERROR XJ004: Database 'Database\TEST_CATS\CAT_CATUSERS_DB\CATUSERS_VERSION_1.0' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 30 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'Database\TEST_CATS\CAT_CATUSERS_DB\CATUSERS_VERSION_1.0' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
============= end nested exception, level (1) ===========
Cleanup action completed
----------------------------------------------------------------
Thu Jul 06 09:25:28 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 65f3c17b-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_CATUSERS_DB\CATUSERS_VERSION_1.0 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Thu Jul 06 09:25:30 CEST 2017:
Shutting down instance 65f3c17b-015d-16c9-d093-000006d71ed8 on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_CATUSERS_DB\CATUSERS_VERSION_1.0 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
----------------------------------------------------------------
Thu Jul 06 09:25:30 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance e21d02a9-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_CATUSERS_DB\CATUSERS_VERSION_1.0 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
Thu Jul 06 09:25:49 CEST 2017 Thread[Thread-32,5,main] Cleanup action starting
java.sql.SQLException: Database 'Database\TEST_CATS\CAT_SAMPUNTYP_DB\SAMPUNTYP_VERSION_2.5' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
Caused by: ERROR XJ004: Database 'Database\TEST_CATS\CAT_SAMPUNTYP_DB\SAMPUNTYP_VERSION_2.5' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 30 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'Database\TEST_CATS\CAT_SAMPUNTYP_DB\SAMPUNTYP_VERSION_2.5' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Jul 06 09:25:49 CEST 2017 Thread[Thread-31,5,main] Cleanup action starting
java.sql.SQLException: Database 'Database\TEST_CATS\CAT_SAMPSTR_DB\SAMPSTR_VERSION_2.5' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
Caused by: ERROR XJ004: Database 'Database\TEST_CATS\CAT_SAMPSTR_DB\SAMPSTR_VERSION_2.5' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 30 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'Database\TEST_CATS\CAT_SAMPSTR_DB\SAMPSTR_VERSION_2.5' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
============= end nested exception, level (1) ===========
Cleanup action completed
----------------------------------------------------------------
Thu Jul 06 09:25:49 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 40558464-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_SAMPUNTYP_DB\SAMPUNTYP_VERSION_2.5 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
----------------------------------------------------------------
Thu Jul 06 09:25:49 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 073cc463-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_SAMPSTR_DB\SAMPSTR_VERSION_2.5 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
Thu Jul 06 09:25:49 CEST 2017 Thread[Thread-34,5,main] Cleanup action starting
java.sql.SQLException: Database 'Database\TEST_CATS\CAT_MDACC_DB\MDACC_VERSION_3.2' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
Caused by: ERROR XJ004: Database 'Database\TEST_CATS\CAT_MDACC_DB\MDACC_VERSION_3.2' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 30 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'Database\TEST_CATS\CAT_MDACC_DB\MDACC_VERSION_3.2' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
============= end nested exception, level (1) ===========
Cleanup action completed
Database Class Loader started - derby.database.classpath=''
Thu Jul 06 09:25:50 CEST 2017 Thread[Thread-36,5,main] Cleanup action starting
java.sql.SQLException: Database 'Database\TEST_CATS\CAT_SAMPNT_DB\SAMPNT_VERSION_3.3' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
Caused by: ERROR XJ004: Database 'Database\TEST_CATS\CAT_SAMPNT_DB\SAMPNT_VERSION_3.3' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 30 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'Database\TEST_CATS\CAT_SAMPNT_DB\SAMPNT_VERSION_3.3' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
============= end nested exception, level (1) ===========
Cleanup action completed
----------------------------------------------------------------
Thu Jul 06 09:25:50 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 6dd50469-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_MDACC_DB\MDACC_VERSION_3.2 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Thu Jul 06 09:25:50 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 0924846c-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_SAMPNT_DB\SAMPNT_VERSION_3.3 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Thu Jul 06 09:25:50 CEST 2017 Thread[Thread-40,5,main] Cleanup action starting
java.sql.SQLException: Database 'Database\TEST_CATS\CAT_MTXTYP_DB\MTXTYP_VERSION_2.1' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
Caused by: ERROR XJ004: Database 'Database\TEST_CATS\CAT_MTXTYP_DB\MTXTYP_VERSION_2.1' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 30 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'Database\TEST_CATS\CAT_MTXTYP_DB\MTXTYP_VERSION_2.1' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Jul 06 09:25:50 CEST 2017 Thread[Thread-38,5,main] Cleanup action starting
java.sql.SQLException: Database 'Database\TEST_CATS\CAT_FAREA_DB\FAREA_VERSION_2.2' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
Caused by: ERROR XJ004: Database 'Database\TEST_CATS\CAT_FAREA_DB\FAREA_VERSION_2.2' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 30 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'Database\TEST_CATS\CAT_FAREA_DB\FAREA_VERSION_2.2' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Jul 06 09:25:50 CEST 2017 Thread[Thread-35,5,main] Cleanup action starting
java.sql.SQLException: Database 'Database\TEST_CATS\CAT_VALTYP_DB\VALTYP_VERSION_2.3' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
Caused by: ERROR XJ004: Database 'Database\TEST_CATS\CAT_VALTYP_DB\VALTYP_VERSION_2.3' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 30 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'Database\TEST_CATS\CAT_VALTYP_DB\VALTYP_VERSION_2.3' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
============= end nested exception, level (1) ===========
Cleanup action completed
----------------------------------------------------------------
Thu Jul 06 09:25:50 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 7fca4472-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_FAREA_DB\FAREA_VERSION_2.2 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
----------------------------------------------------------------
Thu Jul 06 09:25:50 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 18e6c473-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_MTXTYP_DB\MTXTYP_VERSION_2.1 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
----------------------------------------------------------------
Thu Jul 06 09:25:50 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 5d5b4477-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_VALTYP_DB\VALTYP_VERSION_2.3 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
Database Class Loader started - derby.database.classpath=''
Thu Jul 06 09:25:50 CEST 2017 Thread[Thread-39,5,main] Cleanup action starting
java.sql.SQLException: Database 'Database\TEST_CATS\CAT_PRGTYP_DB\PRGTYP_VERSION_2.5' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
Caused by: ERROR XJ004: Database 'Database\TEST_CATS\CAT_PRGTYP_DB\PRGTYP_VERSION_2.5' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 30 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'Database\TEST_CATS\CAT_PRGTYP_DB\PRGTYP_VERSION_2.5' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
============= end nested exception, level (1) ===========
Cleanup action completed
Database Class Loader started - derby.database.classpath=''
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Thu Jul 06 09:25:51 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance a1d3c47b-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_PRGTYP_DB\PRGTYP_VERSION_2.5 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Thu Jul 06 09:25:51 CEST 2017 Thread[Thread-33,5,main] Cleanup action starting
java.sql.SQLException: Database 'Database\TEST_CATS\CAT_POSNEG_DB\POSNEG_VERSION_2.3' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
Caused by: ERROR XJ004: Database 'Database\TEST_CATS\CAT_POSNEG_DB\POSNEG_VERSION_2.3' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 30 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'Database\TEST_CATS\CAT_POSNEG_DB\POSNEG_VERSION_2.3' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
============= end nested exception, level (1) ===========
Cleanup action completed
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Thu Jul 06 09:25:51 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 08900481-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_POSNEG_DB\POSNEG_VERSION_2.3 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Thu Jul 06 09:25:51 CEST 2017 Thread[Thread-41,5,main] Cleanup action starting
java.sql.SQLException: Database 'Database\TEST_CATS\CAT_COUNTRY_DB\COUNTRY_VERSION_2.11' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
Caused by: ERROR XJ004: Database 'Database\TEST_CATS\CAT_COUNTRY_DB\COUNTRY_VERSION_2.11' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 30 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'Database\TEST_CATS\CAT_COUNTRY_DB\COUNTRY_VERSION_2.11' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Jul 06 09:25:51 CEST 2017 Thread[Thread-37,5,main] Cleanup action starting
java.sql.SQLException: Database 'Database\TEST_CATS\CAT_ANLYREFMD_DB\ANLYREFMD_VERSION_1.2' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
Caused by: ERROR XJ004: Database 'Database\TEST_CATS\CAT_ANLYREFMD_DB\ANLYREFMD_VERSION_1.2' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 30 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'Database\TEST_CATS\CAT_ANLYREFMD_DB\ANLYREFMD_VERSION_1.2' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
============= end nested exception, level (1) ===========
Cleanup action completed
----------------------------------------------------------------
Thu Jul 06 09:25:51 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 63f18484-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_COUNTRY_DB\COUNTRY_VERSION_2.11 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
----------------------------------------------------------------
Thu Jul 06 09:25:51 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 6f554487-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_ANLYREFMD_DB\ANLYREFMD_VERSION_1.2 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
Database Class Loader started - derby.database.classpath=''
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Thu Jul 06 09:25:56 CEST 2017:
Shutting down instance 40558464-015d-16c9-d093-000006d71ed8 on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_SAMPUNTYP_DB\SAMPUNTYP_VERSION_2.5 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
----------------------------------------------------------------
Thu Jul 06 09:25:57 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 92ec8fd5-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_SAMPUNTYP_DB\SAMPUNTYP_VERSION_2.5 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Thu Jul 06 09:25:58 CEST 2017:
Shutting down instance 6dd50469-015d-16c9-d093-000006d71ed8 on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_MDACC_DB\MDACC_VERSION_3.2 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
----------------------------------------------------------------
Thu Jul 06 09:25:58 CEST 2017:
Shutting down instance 073cc463-015d-16c9-d093-000006d71ed8 on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_SAMPSTR_DB\SAMPSTR_VERSION_2.5 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
----------------------------------------------------------------
Thu Jul 06 09:25:58 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance f02b10e8-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_MDACC_DB\MDACC_VERSION_3.2 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Thu Jul 06 09:25:58 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance ae605102-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_SAMPSTR_DB\SAMPSTR_VERSION_2.5 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
----------------------------------------------------------------
Thu Jul 06 09:25:59 CEST 2017:
Shutting down instance 7fca4472-015d-16c9-d093-000006d71ed8 on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_FAREA_DB\FAREA_VERSION_2.2 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Thu Jul 06 09:25:59 CEST 2017:
Shutting down instance 18e6c473-015d-16c9-d093-000006d71ed8 on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_MTXTYP_DB\MTXTYP_VERSION_2.1 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
----------------------------------------------------------------
Thu Jul 06 09:25:59 CEST 2017:
Shutting down instance 0924846c-015d-16c9-d093-000006d71ed8 on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_SAMPNT_DB\SAMPNT_VERSION_3.3 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
----------------------------------------------------------------
Thu Jul 06 09:26:01 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 8743d1fb-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_MTXTYP_DB\MTXTYP_VERSION_2.1 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
----------------------------------------------------------------
Thu Jul 06 09:26:01 CEST 2017:
Shutting down instance 5d5b4477-015d-16c9-d093-000006d71ed8 on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_VALTYP_DB\VALTYP_VERSION_2.3 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
----------------------------------------------------------------
Thu Jul 06 09:26:01 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 67c19204-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_SAMPNT_DB\SAMPNT_VERSION_3.3 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Thu Jul 06 09:26:01 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 736ad213-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_FAREA_DB\FAREA_VERSION_2.2 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
----------------------------------------------------------------
Thu Jul 06 09:26:01 CEST 2017:
Shutting down instance a1d3c47b-015d-16c9-d093-000006d71ed8 on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_PRGTYP_DB\PRGTYP_VERSION_2.5 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
----------------------------------------------------------------
Thu Jul 06 09:26:01 CEST 2017:
Shutting down instance 63f18484-015d-16c9-d093-000006d71ed8 on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_COUNTRY_DB\COUNTRY_VERSION_2.11 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Thu Jul 06 09:26:02 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 4eda1230-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_VALTYP_DB\VALTYP_VERSION_2.3 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Thu Jul 06 09:26:03 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 29a6d273-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_PRGTYP_DB\PRGTYP_VERSION_2.5 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Thu Jul 06 09:26:04 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 399b1299-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_COUNTRY_DB\COUNTRY_VERSION_2.11 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
----------------------------------------------------------------
Thu Jul 06 09:26:04 CEST 2017:
Shutting down instance 08900481-015d-16c9-d093-000006d71ed8 on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_POSNEG_DB\POSNEG_VERSION_2.3 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Thu Jul 06 09:26:04 CEST 2017:
Shutting down instance 6f554487-015d-16c9-d093-000006d71ed8 on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_ANLYREFMD_DB\ANLYREFMD_VERSION_1.2 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
----------------------------------------------------------------
Thu Jul 06 09:26:07 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance ae1f1348-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_POSNEG_DB\POSNEG_VERSION_2.3 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Thu Jul 06 09:26:07 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 0864d35e-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_ANLYREFMD_DB\ANLYREFMD_VERSION_1.2 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
Thu Jul 06 09:26:16 CEST 2017 Thread[Thread-75,5,main] Cleanup action starting
java.sql.SQLException: Database 'Database\TEST_CATS\CAT_PARAM_DB\PARAM_VERSION_9.0' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
Caused by: ERROR XJ004: Database 'Database\TEST_CATS\CAT_PARAM_DB\PARAM_VERSION_9.0' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 30 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'Database\TEST_CATS\CAT_PARAM_DB\PARAM_VERSION_9.0' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at catalogue.Catalogue.getConnection(Catalogue.java:2195)
	at import_catalogue.CatalogueSheetImporter.createDatabase(CatalogueSheetImporter.java:186)
	at import_catalogue.CatalogueSheetImporter.insert(CatalogueSheetImporter.java:169)
	at import_catalogue.SheetImporter.importData(SheetImporter.java:61)
	at import_catalogue.CatalogueWorkbookImporter.importCatalogueSheet(CatalogueWorkbookImporter.java:213)
	at import_catalogue.CatalogueWorkbookImporter.access$0(CatalogueWorkbookImporter.java:196)
	at import_catalogue.CatalogueWorkbookImporter$1.execute(CatalogueWorkbookImporter.java:100)
	at ui_progress_bar.ProgressStep.start(ProgressStep.java:59)
	at ui_progress_bar.ProgressList.start(ProgressList.java:62)
	at import_catalogue.CatalogueWorkbookImporter.importWorkbook(CatalogueWorkbookImporter.java:163)
	at import_catalogue.CatalogueImporter.importXlsx(CatalogueImporter.java:203)
	at import_catalogue.CatalogueImporter.importXml(CatalogueImporter.java:183)
	at import_catalogue.CatalogueImporter.makeImport(CatalogueImporter.java:67)
	at import_catalogue.CatalogueImporterThread.run(CatalogueImporterThread.java:86)
============= end nested exception, level (1) ===========
Cleanup action completed
----------------------------------------------------------------
Thu Jul 06 09:26:16 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance b08b53f7-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_PARAM_DB\PARAM_VERSION_9.0 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Thu Jul 06 09:26:18 CEST 2017:
Shutting down instance b08b53f7-015d-16c9-d093-000006d71ed8 on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_PARAM_DB\PARAM_VERSION_9.0 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
----------------------------------------------------------------
Thu Jul 06 09:26:18 CEST 2017:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.12.1.1 - (1704137): instance 20469525-015d-16c9-d093-000006d71ed8 
on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\TEST_CATS\CAT_PARAM_DB\PARAM_VERSION_9.0 with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
Loaded from file:/C:/Users/avonva/Desktop/CatalogueBrowser/CatalogueBrowser/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Thu Jul 06 09:26:20 CEST 2017:
Shutting down instance a816c00e-015d-16c9-d093-000006d71ed8 on database directory C:\Users\avonva\Desktop\CatalogueBrowser\CatalogueBrowser\Database\MAIN_CATS_DB with class loader sun.misc.Launcher$AppClassLoader@73d16e93 
